In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from BHDVCS_tf_modified import *

In [2]:
fns = F1F2()
calc = F_calc()

In [3]:
########## INPUT from the User ###################
interval = 10  # This the interval for angle (phi) binning
### Kinematics file ####
file_name = 'AllJlabData.csv'
########## The input parameters for a, b, c, d, e, f need to be provided below #####


kindf = pd.read_csv(file_name, dtype=np.float32).dropna(axis=0, how='all').dropna(axis=1, how='all')

In [4]:
kindf

,#Set,index,k,QQ,x_b,t,phi_x,F,sigmaF,varF,F1,F2
0,1.0,0.0,5.750,1.82,0.343,-0.172,7.5,0.1116,0.00492,0.04409,0.68309,1.09312
1,1.0,1.0,5.750,1.82,0.343,-0.172,22.5,0.1176,0.00468,0.03980,0.68309,1.09312
2,1.0,2.0,5.750,1.82,0.343,-0.172,37.5,0.0998,0.00420,0.04208,0.68309,1.09312
3,1.0,3.0,5.750,1.82,0.343,-0.172,52.5,0.0941,0.00396,0.04208,0.68309,1.09312
4,1.0,4.0,5.750,1.82,0.343,-0.172,67.5,0.0882,0.00360,0.04082,0.68309,1.09312
...,...,...,...,...,...,...,...,...,...,...,...,...
4675,195.0,19.0,4.455,2.00,0.360,-0.304,292.5,0.0793,0.00735,0.09271,0.54532,0.80365
4676,195.0,20.0,4.455,2.00,0.360,-0.304,307.5,0.1350,0.00998,0.07395,0.54532,0.80365
4677,195.0,21.0,4.455,2.00,0.360,-0.304,322.5,0.1505,0.01201,0.07979,0.54532,0.80365
4678,195.0,22.0,4.455,2.00,0.360,-0.304,337.5,0.1660,0.01877,0.11306,0.54532,0.80365
4679,195.0,23.0,4.455,2.00,0.360,-0.304,352.5,0.0000,0.00000,0.00000,0.00000,0.00000